<div class="newsletter-mobile hidden-md visible-xs">
    <?php echo $this->getLayout()->createBlock("Magento\Newsletter\Block\Subscribe")->setTemplate("Magento_Newsletter::subscribe.phtml")->toHtml();?>
    <div class="social-mobile hidden-md visible-xs">
        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_social_icons_faviana')->toHtml();?>
    </div>
</div>