<?php $_celebritycategory = $this->getCollection(); ?>
<?php if ($_celebritycategory->getSize()): ?>
<div class="celebritycategory_list_view">
    <?php foreach ($_celebritycategory as $celebritycategoryItem): ?>
        <div id="item_<?php echo $celebritycategoryItem->getId() ?>" class="celebritycategory_list_item">
            <h2>
                <a href="<?php echo $this->getItemUrl($celebritycategoryItem) ?>">
                    <?php echo $this->escapeHtml($celebritycategoryItem->getTitle()) ?>
                </a>
            </h2>

            <div class="celebritycategory_item_subtitle">
                <?php echo $this->formatDate($celebritycategoryItem->getPublishedAt()) ?> |
                <?php echo $this->escapeHtml($celebritycategoryItem->getAuthor()) ?>
            </div>

            <?php if ($imageUrl = $this->getImageUrl($celebritycategoryItem, 100)): ?>
               <p><img src="<?php echo $imageUrl ?>" alt="<?php echo $this->escapeHtml($celebritycategoryItem->getTitle()); ?>" /></p>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>
</div>
<?php echo $this->getPager() ?>
<?php else: ?>
    <div class="message info empty"><span><?php echo __('You have no Celebritycategory.'); ?></span></div>
<?php endif ?>
