<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View*/
?>
<?php
$_product = $block->getProduct();
$_wishlistSubmitParams = $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($_product);
$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
?>

<div class="product-addto-links1 row" data-role="add-to-links">
    <div class="col-sm-6">
        <a href="javascript:void(0)" class="btn btn-black find-btn">FIND A STORE NEAR YOU</a>
    </div>
    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()) : ?>
        <div class="col-sm-6">
            <a href="#"
            class="action1 towishlist wish-btn btn"
            data-post='<?php /* @escapeNotVerified */ echo $_wishlistSubmitParams; ?>'
            data-action="add-to-wishlist"><span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span></a>
        </div>
    <?php endif; ?>
        <?php /* ?>
        <div class="col-sm-6">
            <a href="#" data-post='<?php  echo $compareHelper->getPostDataParams($_product);?>'
        data-role="add-to-links"
        class="action1 tocompare btn btn-black find-btn"><span><?php echo __('Add to Compare') ?></span></a>
        </div>
        <?php */ ?>
</div>
<script type="text/x-magento-init">
    {
        "body": {
            "addToWishlist": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($block->getWishlistOptions())?>
        }
    }
</script>
