<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="Products-section">
	<div class="container inner-wrapper">
		<div class="row">
<form class="form contact enquiryform"
      action="<?php /* @escapeNotVerified */ echo $block->getEnquiryFormAction(); ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Write Us') ?></span></legend><br />
        <div class="field note no-label"><?php /* @escapeNotVerified */ echo __('If you have any question so Just send a Enquiry and we’ll get back to you as quickly as possible.') ?></div>
        <div class="field subject required">
            <label class="label" for="subject"><span><?php /* @escapeNotVerified */ echo __('Subject') ?></span></label>
            <div class="control">
                <select name="subject" id="subject" data-validate="{required:true}">
					<option value="Invitation to Tender"><?php echo __('Invitation to Tender');?></option>
					<option value="Information request"><?php echo __('Information request');?></option>
					<option value="General"><?php echo __('General');?></option>
				</select>
            </div>
        </div>
		<div class="field name required">
            <label class="label" for="name"><span><?php /* @escapeNotVerified */ echo __('Name') ?></span></label>
            <div class="control">
                <input name="name" id="name" title="<?php /* @escapeNotVerified */ echo __('Name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
		<div class="field company required">
            <label class="label" for="company"><span><?php /* @escapeNotVerified */ echo __('Company Name') ?></span></label>
            <div class="control">
                <input name="company" id="company" title="<?php /* @escapeNotVerified */ echo __('Company Name') ?>" value="" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
		<div class="field job required">
            <label class="label" for="job"><span><?php /* @escapeNotVerified */ echo __('Job') ?></span></label>
            <div class="control">
                <input name="job" id="job" title="<?php /* @escapeNotVerified */ echo __('Job') ?>" value="" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
		
        <div class="field email required">
            <label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
            <div class="control">
                <input name="email" id="email" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>
        <div class="field telephone">
            <label class="label" for="telephone"><span><?php /* @escapeNotVerified */ echo __('Telephone number') ?></span></label>
            <div class="control">
                <input name="telephone" id="telephone" title="<?php /* @escapeNotVerified */ echo __('Telephone number') ?>" value="" class="input-text" type="text" />
            </div>
        </div>
		<div class="field zipcode required">
            <label class="label" for="zipcode"><span><?php /* @escapeNotVerified */ echo __('Zipcode') ?></span></label>
            <div class="control">
                <input name="zipcode" id="zipcode" title="<?php /* @escapeNotVerified */ echo __('Zipcode') ?>" value="" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
		<div class="field place">
            <label class="label" for="place"><span><?php /* @escapeNotVerified */ echo __('Place') ?></span></label>
            <div class="control">
                <input name="place" id="place" title="<?php /* @escapeNotVerified */ echo __('Place') ?>" class="input-text" type="text"/>
            </div>
        </div>
       <div class="field comment">
            <label class="label" for="comment"><span><?php /* @escapeNotVerified */ echo __('Possible questions or remarks') ?></span></label>
            <div class="control">
                <textarea name="comment" id="comment" title="<?php /* @escapeNotVerified */ echo __('Possible questions or remarks') ?>" class="input-text" cols="5" rows="3"></textarea>
            </div>
        </div> 
        <div class="actions-toolbar">
        <div class="primary">
           
            <button type="submit" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>" class="action submit primary">
                <span><?php /* @escapeNotVerified */ echo __('Send Enquiry') ?></span>
            </button>
        </div>
    </div>
        <?php echo $block->getChildHtml('form.additional.info'); ?>
    </fieldset>
    
</form>
</div>
    </div>
</div>